default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending

-   repo: https://github.com/crate-ci/committed
    rev: v1.0.20
    hooks:
    -   id: committed

-   repo: https://github.com/doublify/pre-commit-rust
    rev: eeee35a89e69d5772bdee97db1a6a898467b686e
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
